name: Suggestion
description: Please provide suggestions on the Upstream Fabric repository, unless you want to make a Neoforge specific compatibility request.
body:
  - type: textarea
    id: suggestion
    attributes:
      label: Suggestion
    validations:
      required: true
